USE ForteData;
GRANT ALTER TO forte;
GRANT CONTROL TO forte;
GRANT CREATE CONTRACT TO forte;
GRANT CREATE MESSAGE TYPE TO forte;
GRANT CREATE PROCEDURE TO forte;
GRANT EXECUTE TO forte;
GRANT SELECT TO forte;
GRANT CREATE QUEUE TO forte;
GRANT CREATE SERVICE TO forte;
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO forte;
GRANT CONNECT TO forte;
GRANT VIEW DATABASE STATE TO forte;
GRANT VIEW DEFINITION TO forte;

