//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForteARP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PORNTEP\\SQLEXPRESS;Initial Catalog=ForteData;Integrated Security=True" +
            "")]
        public string ForteDataConnectionString {
            get {
                return ((string)(this["ForteDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("forte")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("etrof")]
        public string PassWord {
            get {
                return ((string)(this["PassWord"]));
            }
            set {
                this["PassWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\SQLEXPRESS")]
        public string RemoteServer {
            get {
                return ((string)(this["RemoteServer"]));
            }
            set {
                this["RemoteServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BSerRemote {
            get {
                return ((bool)(this["BSerRemote"]));
            }
            set {
                this["BSerRemote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp")]
        public string CsvFileLocation {
            get {
                return ((string)(this["CsvFileLocation"]));
            }
            set {
                this["CsvFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ForteData")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
            set {
                this["Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string Host {
            get {
                return ((string)(this["Host"]));
            }
            set {
                this["Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLEXPRESS")]
        public string Instance {
            get {
                return ((string)(this["Instance"]));
            }
            set {
                this["Instance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Local {
            get {
                return ((bool)(this["Local"]));
            }
            set {
                this["Local"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WeightUnit {
            get {
                return ((int)(this["WeightUnit"]));
            }
            set {
                this["WeightUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MoistureUnit {
            get {
                return ((int)(this["MoistureUnit"]));
            }
            set {
                this["MoistureUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ForteLayer")]
        public string WLDatabase {
            get {
                return ((string)(this["WLDatabase"]));
            }
            set {
                this["WLDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox1 {
            get {
                return ((int)(this["iRTBox1"]));
            }
            set {
                this["iRTBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox2 {
            get {
                return ((int)(this["iRTBox2"]));
            }
            set {
                this["iRTBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox3 {
            get {
                return ((int)(this["iRTBox3"]));
            }
            set {
                this["iRTBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox4 {
            get {
                return ((int)(this["iRTBox4"]));
            }
            set {
                this["iRTBox4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox5 {
            get {
                return ((int)(this["iRTBox5"]));
            }
            set {
                this["iRTBox5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox6 {
            get {
                return ((int)(this["iRTBox6"]));
            }
            set {
                this["iRTBox6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTBox7 {
            get {
                return ((int)(this["iRTBox7"]));
            }
            set {
                this["iRTBox7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iCbServerSelect {
            get {
                return ((int)(this["iCbServerSelect"]));
            }
            set {
                this["iCbServerSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalHost {
            get {
                return ((string)(this["LocalHost"]));
            }
            set {
                this["LocalHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bBalerType {
            get {
                return ((bool)(this["bBalerType"]));
            }
            set {
                this["bBalerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuEight {
            get {
                return ((float)(this["GraphHiMenuEight"]));
            }
            set {
                this["GraphHiMenuEight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuEight {
            get {
                return ((float)(this["GraphLoMenuEight"]));
            }
            set {
                this["GraphLoMenuEight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ibaleSamples {
            get {
                return ((int)(this["ibaleSamples"]));
            }
            set {
                this["ibaleSamples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iMenuSelected {
            get {
                return ((int)(this["iMenuSelected"]));
            }
            set {
                this["iMenuSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuOne {
            get {
                return ((float)(this["GraphHiMenuOne"]));
            }
            set {
                this["GraphHiMenuOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuOne {
            get {
                return ((float)(this["GraphLoMenuOne"]));
            }
            set {
                this["GraphLoMenuOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuTwo {
            get {
                return ((float)(this["GraphHiMenuTwo"]));
            }
            set {
                this["GraphHiMenuTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuTwo {
            get {
                return ((float)(this["GraphLoMenuTwo"]));
            }
            set {
                this["GraphLoMenuTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int iScanRate {
            get {
                return ((int)(this["iScanRate"]));
            }
            set {
                this["iScanRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int iWLSamples {
            get {
                return ((int)(this["iWLSamples"]));
            }
            set {
                this["iWLSamples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WLMinLimit {
            get {
                return ((double)(this["WLMinLimit"]));
            }
            set {
                this["WLMinLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WLMaxLimit {
            get {
                return ((double)(this["WLMaxLimit"]));
            }
            set {
                this["WLMaxLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"0\"")]
        public string WLMinYAxis {
            get {
                return ((string)(this["WLMinYAxis"]));
            }
            set {
                this["WLMinYAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"40\"")]
        public string WLMaxYAxis {
            get {
                return ((string)(this["WLMaxYAxis"]));
            }
            set {
                this["WLMaxYAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WLYAxisInterval {
            get {
                return ((int)(this["WLYAxisInterval"]));
            }
            set {
                this["WLYAxisInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WLHiColorIndex {
            get {
                return ((int)(this["WLHiColorIndex"]));
            }
            set {
                this["WLHiColorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WLNormColorIndex {
            get {
                return ((int)(this["WLNormColorIndex"]));
            }
            set {
                this["WLNormColorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WLLoColorIndex {
            get {
                return ((int)(this["WLLoColorIndex"]));
            }
            set {
                this["WLLoColorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WLAlarmIndex {
            get {
                return ((int)(this["WLAlarmIndex"]));
            }
            set {
                this["WLAlarmIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WLOkIndex {
            get {
                return ((int)(this["WLOkIndex"]));
            }
            set {
                this["WLOkIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int iDropProfile {
            get {
                return ((int)(this["iDropProfile"]));
            }
            set {
                this["iDropProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropProBox1 {
            get {
                return ((int)(this["iDropProBox1"]));
            }
            set {
                this["iDropProBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropProBox2 {
            get {
                return ((int)(this["iDropProBox2"]));
            }
            set {
                this["iDropProBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropProBox3 {
            get {
                return ((int)(this["iDropProBox3"]));
            }
            set {
                this["iDropProBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropProBox4 {
            get {
                return ((int)(this["iDropProBox4"]));
            }
            set {
                this["iDropProBox4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bAutoSetMod {
            get {
                return ((bool)(this["bAutoSetMod"]));
            }
            set {
                this["bAutoSetMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWetLayer {
            get {
                return ((bool)(this["bWetLayer"]));
            }
            set {
                this["bWetLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bDropOptions {
            get {
                return ((bool)(this["bDropOptions"]));
            }
            set {
                this["bDropOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int iDropGraphSamples {
            get {
                return ((int)(this["iDropGraphSamples"]));
            }
            set {
                this["iDropGraphSamples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bModOveride {
            get {
                return ((bool)(this["bModOveride"]));
            }
            set {
                this["bModOveride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int iWetLayerTrendSample {
            get {
                return ((int)(this["iWetLayerTrendSample"]));
            }
            set {
                this["iWetLayerTrendSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bLogMsgOn {
            get {
                return ((bool)(this["bLogMsgOn"]));
            }
            set {
                this["bLogMsgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int iMaxLogLines {
            get {
                return ((int)(this["iMaxLogLines"]));
            }
            set {
                this["iMaxLogLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bDropHitoLow {
            get {
                return ((bool)(this["bDropHitoLow"]));
            }
            set {
                this["bDropHitoLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bDropPosition {
            get {
                return ((bool)(this["bDropPosition"]));
            }
            set {
                this["bDropPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDualGraphLineindex {
            get {
                return ((int)(this["iDualGraphLineindex"]));
            }
            set {
                this["iDualGraphLineindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int iDualGraphSamples {
            get {
                return ((int)(this["iDualGraphSamples"]));
            }
            set {
                this["iDualGraphSamples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropGraphLineIndex {
            get {
                return ((int)(this["iDropGraphLineIndex"]));
            }
            set {
                this["iDropGraphLineIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropProfileLineIndex {
            get {
                return ((int)(this["iDropProfileLineIndex"]));
            }
            set {
                this["iDropProfileLineIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bDropNumbers {
            get {
                return ((bool)(this["bDropNumbers"]));
            }
            set {
                this["bDropNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iBalesInADrop {
            get {
                return ((int)(this["iBalesInADrop"]));
            }
            set {
                this["iBalesInADrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int iDropSample {
            get {
                return ((int)(this["iDropSample"]));
            }
            set {
                this["iDropSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropProfileSourceIndex {
            get {
                return ((int)(this["iDropProfileSourceIndex"]));
            }
            set {
                this["iDropProfileSourceIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuFive {
            get {
                return ((float)(this["GraphHiMenuFive"]));
            }
            set {
                this["GraphHiMenuFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuFive {
            get {
                return ((float)(this["GraphLoMenuFive"]));
            }
            set {
                this["GraphLoMenuFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuSix {
            get {
                return ((float)(this["GraphHiMenuSix"]));
            }
            set {
                this["GraphHiMenuSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuSix {
            get {
                return ((float)(this["GraphLoMenuSix"]));
            }
            set {
                this["GraphLoMenuSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRTGMenuSelected {
            get {
                return ((int)(this["iRTGMenuSelected"]));
            }
            set {
                this["iRTGMenuSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuSeven {
            get {
                return ((float)(this["GraphHiMenuSeven"]));
            }
            set {
                this["GraphHiMenuSeven"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuSeven {
            get {
                return ((float)(this["GraphLoMenuSeven"]));
            }
            set {
                this["GraphLoMenuSeven"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuThree {
            get {
                return ((float)(this["GraphHiMenuThree"]));
            }
            set {
                this["GraphHiMenuThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuThree {
            get {
                return ((float)(this["GraphLoMenuThree"]));
            }
            set {
                this["GraphLoMenuThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WLDayEndTime {
            get {
                return ((string)(this["WLDayEndTime"]));
            }
            set {
                this["WLDayEndTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphHiMenuFour {
            get {
                return ((float)(this["GraphHiMenuFour"]));
            }
            set {
                this["GraphHiMenuFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GraphLoMenuFour {
            get {
                return ((float)(this["GraphLoMenuFour"]));
            }
            set {
                this["GraphLoMenuFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropGraphMenuSel {
            get {
                return ((int)(this["iDropGraphMenuSel"]));
            }
            set {
                this["iDropGraphMenuSel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDualGraphSourceindex {
            get {
                return ((int)(this["iDualGraphSourceindex"]));
            }
            set {
                this["iDualGraphSourceindex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"1\"")]
        public string sDualGraphSourceSel {
            get {
                return ((string)(this["sDualGraphSourceSel"]));
            }
            set {
                this["sDualGraphSourceSel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"1\"")]
        public string sDualGraphLineSel {
            get {
                return ((string)(this["sDualGraphLineSel"]));
            }
            set {
                this["sDualGraphLineSel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iDropGraphSourceIndex {
            get {
                return ((int)(this["iDropGraphSourceIndex"]));
            }
            set {
                this["iDropGraphSourceIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"1\"")]
        public string sGrphProfileSourceSel {
            get {
                return ((string)(this["sGrphProfileSourceSel"]));
            }
            set {
                this["sGrphProfileSourceSel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bNetWork {
            get {
                return ((bool)(this["bNetWork"]));
            }
            set {
                this["bNetWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxOne {
            get {
                return ((int)(this["iVarBoxOne"]));
            }
            set {
                this["iVarBoxOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxTwo {
            get {
                return ((int)(this["iVarBoxTwo"]));
            }
            set {
                this["iVarBoxTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxThree {
            get {
                return ((int)(this["iVarBoxThree"]));
            }
            set {
                this["iVarBoxThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxFour {
            get {
                return ((int)(this["iVarBoxFour"]));
            }
            set {
                this["iVarBoxFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxFive {
            get {
                return ((int)(this["iVarBoxFive"]));
            }
            set {
                this["iVarBoxFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxSix {
            get {
                return ((int)(this["iVarBoxSix"]));
            }
            set {
                this["iVarBoxSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxSeven {
            get {
                return ((int)(this["iVarBoxSeven"]));
            }
            set {
                this["iVarBoxSeven"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxEight {
            get {
                return ((int)(this["iVarBoxEight"]));
            }
            set {
                this["iVarBoxEight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxNine {
            get {
                return ((int)(this["iVarBoxNine"]));
            }
            set {
                this["iVarBoxNine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxTen {
            get {
                return ((int)(this["iVarBoxTen"]));
            }
            set {
                this["iVarBoxTen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxEleven {
            get {
                return ((int)(this["iVarBoxEleven"]));
            }
            set {
                this["iVarBoxEleven"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iVarBoxTwelve {
            get {
                return ((int)(this["iVarBoxTwelve"]));
            }
            set {
                this["iVarBoxTwelve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HistLowLimits {
            get {
                return ((int)(this["HistLowLimits"]));
            }
            set {
                this["HistLowLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int HistHiLimits {
            get {
                return ((int)(this["HistHiLimits"]));
            }
            set {
                this["HistHiLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HisHiColorIndex {
            get {
                return ((int)(this["HisHiColorIndex"]));
            }
            set {
                this["HisHiColorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HisCHiColorIndex {
            get {
                return ((int)(this["HisCHiColorIndex"]));
            }
            set {
                this["HisCHiColorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HisNorColorIndex {
            get {
                return ((int)(this["HisNorColorIndex"]));
            }
            set {
                this["HisNorColorIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"0\"")]
        public string sRealTimeSource {
            get {
                return ((string)(this["sRealTimeSource"]));
            }
            set {
                this["sRealTimeSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRealTimeSourceIdx {
            get {
                return ((int)(this["iRealTimeSourceIdx"]));
            }
            set {
                this["iRealTimeSourceIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iRealTimeLineidx {
            get {
                return ((int)(this["iRealTimeLineidx"]));
            }
            set {
                this["iRealTimeLineidx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"0\"")]
        public string sRealTimeLine {
            get {
                return ((string)(this["sRealTimeLine"]));
            }
            set {
                this["sRealTimeLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bSelectLine {
            get {
                return ((bool)(this["bSelectLine"]));
            }
            set {
                this["bSelectLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int iRealTimeBale {
            get {
                return ((int)(this["iRealTimeBale"]));
            }
            set {
                this["iRealTimeBale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int iLanguageIdx {
            get {
                return ((int)(this["iLanguageIdx"]));
            }
            set {
                this["iLanguageIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bBSqlDep {
            get {
                return ((bool)(this["bBSqlDep"]));
            }
            set {
                this["bBSqlDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelTimeEndIndex {
            get {
                return ((int)(this["SelTimeEndIndex"]));
            }
            set {
                this["SelTimeEndIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DayEndTime {
            get {
                return ((string)(this["DayEndTime"]));
            }
            set {
                this["DayEndTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShowHistrogram {
            get {
                return ((bool)(this["bShowHistrogram"]));
            }
            set {
                this["bShowHistrogram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bWlShowTrend {
            get {
                return ((bool)(this["bWlShowTrend"]));
            }
            set {
                this["bWlShowTrend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShowProdEstimate {
            get {
                return ((bool)(this["bShowProdEstimate"]));
            }
            set {
                this["bShowProdEstimate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ProdDayEnd {
            get {
                return ((global::System.DateTime)(this["ProdDayEnd"]));
            }
            set {
                this["ProdDayEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowM {
            get {
                return ((float)(this["dYxLowM"]));
            }
            set {
                this["dYxLowM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowW {
            get {
                return ((float)(this["dYxLowW"]));
            }
            set {
                this["dYxLowW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowADWt {
            get {
                return ((float)(this["dYxLowADWt"]));
            }
            set {
                this["dYxLowADWt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowDirt {
            get {
                return ((float)(this["dYxLowDirt"]));
            }
            set {
                this["dYxLowDirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowBright {
            get {
                return ((float)(this["dYxLowBright"]));
            }
            set {
                this["dYxLowBright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float dYxHiM {
            get {
                return ((float)(this["dYxHiM"]));
            }
            set {
                this["dYxHiM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float dYxHiW {
            get {
                return ((float)(this["dYxHiW"]));
            }
            set {
                this["dYxHiW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float dYxHiBdWt {
            get {
                return ((float)(this["dYxHiBdWt"]));
            }
            set {
                this["dYxHiBdWt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float dYxHiADWt {
            get {
                return ((float)(this["dYxHiADWt"]));
            }
            set {
                this["dYxHiADWt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float dYxHiDirt {
            get {
                return ((float)(this["dYxHiDirt"]));
            }
            set {
                this["dYxHiDirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float dYxHiBright {
            get {
                return ((float)(this["dYxHiBright"]));
            }
            set {
                this["dYxHiBright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BScaleAuto {
            get {
                return ((bool)(this["BScaleAuto"]));
            }
            set {
                this["BScaleAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowBdWt {
            get {
                return ((float)(this["dYxLowBdWt"]));
            }
            set {
                this["dYxLowBdWt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxHiVisco {
            get {
                return ((float)(this["dYxHiVisco"]));
            }
            set {
                this["dYxHiVisco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dYxLowVisco {
            get {
                return ((float)(this["dYxLowVisco"]));
            }
            set {
                this["dYxLowVisco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool archCheck {
            get {
                return ((bool)(this["archCheck"]));
            }
            set {
                this["archCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool realTimeDataCheck {
            get {
                return ((bool)(this["realTimeDataCheck"]));
            }
            set {
                this["realTimeDataCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool realTimeGrpCheck {
            get {
                return ((bool)(this["realTimeGrpCheck"]));
            }
            set {
                this["realTimeGrpCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool relTimeDualGrpCheck {
            get {
                return ((bool)(this["relTimeDualGrpCheck"]));
            }
            set {
                this["relTimeDualGrpCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool wetLayerChecked {
            get {
                return ((bool)(this["wetLayerChecked"]));
            }
            set {
                this["wetLayerChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool variablesCheck {
            get {
                return ((bool)(this["variablesCheck"]));
            }
            set {
                this["variablesCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int backgndchartidx {
            get {
                return ((int)(this["backgndchartidx"]));
            }
            set {
                this["backgndchartidx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int graphByLstidx {
            get {
                return ((int)(this["graphByLstidx"]));
            }
            set {
                this["graphByLstidx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DropChecked {
            get {
                return ((bool)(this["DropChecked"]));
            }
            set {
                this["DropChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DpProfileChecked {
            get {
                return ((bool)(this["DpProfileChecked"]));
            }
            set {
                this["DpProfileChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DropGraphChecked {
            get {
                return ((bool)(this["DropGraphChecked"]));
            }
            set {
                this["DropGraphChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DropPosChecked {
            get {
                return ((bool)(this["DropPosChecked"]));
            }
            set {
                this["DropPosChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteProfileChecked {
            get {
                return ((bool)(this["RemoteProfileChecked"]));
            }
            set {
                this["RemoteProfileChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CombindGrpSample {
            get {
                return ((int)(this["CombindGrpSample"]));
            }
            set {
                this["CombindGrpSample"] = value;
            }
        }
    }
}
